<a href="https://colab.research.google.com/github/Rohanjain1211/UML501_Rohan_Jain_102303740/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1.A)


In [ ]:
# A)
import numpy as np

arr = np.array([1, 2, 8, 9, 4, 5])
revarr =np.flip(arr)
print(revarr)

[5 4 9 8 2 1]


1b


In [ ]:
# Use arr.flatten
arr1=np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatten_arr=arr1.flatten()
print(flatten_arr)


[1 2 3 2 4 5 1 2 3]


1c)


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1,arr2)

True

1d)


In [ ]:
import numpy as np

#1)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_frequent_value = np.bincount(x).argmax()
indices = np.where(x == most_frequent_value)[0]

print(f"The most frequent value is: {most_frequent_value}")
print(f"The indices are: {indices}")

#2

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent = np.bincount(y).argmax()
indice = np.where(y == most_frequent)[0]

print(f"The most frequent value is: {most_frequent}")
print(f"The indices are: {indice}")


The most frequent value is: 1
The indices are: [0 5 7 8 9]
The most frequent value is: 1
The indices are: [0 1 2]


1.e)

In [ ]:
#1)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
totalsum=np.sum(gfg)
print("Total sum:",totalsum)
#2)

rowsum=gfg.sum(axis=0)
print("Row sum:",rowsum)
#3)
colsum=gfg.sum(axis=1)
print("Column sum:",colsum)

Total sum: 45
Row sum: [[20  9 16]]
Column sum: [[14]
 [16]
 [15]]


1.f)

In [ ]:
#1
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

diagonal_sum=np.trace(n_array)
print("Diagonal sum:",diagonal_sum)

#2
eigen_val=np.linalg.eigvals(n_array)
print("Eigen values:",eigen_val)

#3

eigen_vector=np.linalg.eig(n_array)
print("Eigen vectors:",eigen_vector)

#4
inverse_arr=np.linalg.inv(n_array)
print("Inverse array:",inverse_arr)

#5
determinant_arr=np.linalg.det(n_array)
print("Determinant:", determinant_arr)

Diagonal sum: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors: EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Inverse array: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


1g)


In [ ]:
import numpy as np

# 1
print("# Part i")

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

# Matrix multiplication
product1 = np.dot(p1, q1)
print("Matrix multiplication (p1 @ q1):\n", product1)

# Covariance between flattened versions
cov1 = np.cov(p1.flatten(), q1.flatten())
print("Covariance matrix:\n", cov1)


# 2
print("\n# Part ii")

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product2 = np.dot(p2, q2)
print("Matrix multiplication (p2 @ q2):\n", product2)

# Covariance between flattened versions
cov2 = np.cov(p2.flatten(), q2.flatten())
print("Covariance matrix:\n",cov2)

# Part i
Matrix multiplication (p1 @ q1):
 [[16 19]
 [26 31]]
Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]

# Part ii
Matrix multiplication (p2 @ q2):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


1 h)


In [ ]:
import numpy as np
from itertools import product

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner Product
inner_product = np.inner(x, y)
print("Inner Product:\n", inner_product)

# Outer Product
outer_product = np.outer(x, y)
print("\nOuter Product:\n", outer_product)


cartesian_product = np.array([np.concatenate((xr, yr)) for xr, yr in product(x, y)])
print("\nCartesian Product (Row combinations):\n", cartesian_product)

Inner Product:
 [[17 52]
 [13 62]]

Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product (Row combinations):
 [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


2a)


In [ ]:

#1)
array = np.array([[1, -2, 3],[-4, 5, -6]])

mod_val=np.abs(array)
print(mod_val)

#2
flat_percentiles = np.percentile(array, [25, 50, 75])
print("\nPercentiles (Flattened array):", flat_percentiles)

# Column-wise
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
print("\nColumn-wise percentiles:\n", col_percentiles)

# Row-wise
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)
print("\nRow-wise percentiles:\n", row_percentiles)

#3

# Flattened
print("Flattened:")
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))

# Column-wise
print("\nColumn-wise:")
print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Standard Deviation:", np.std(array, axis=0))

# Row-wise
print("\nRow-wise:")
print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Standard Deviation:", np.std(array, axis=1))

[[1 2 3]
 [4 5 6]]

Percentiles (Flattened array): [-3.5 -0.5  2.5]

Column-wise percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Row-wise percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Column-wise:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Row-wise:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


2b)


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

print("Original:   ", a)
print("Floor:      ", floor_vals)
print("Ceiling:    ", ceil_vals)
print("Truncated:  ", trunc_vals)
print("Rounded:    ", round_vals)

Original:    [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor:       [-2. -2. -1.  0.  1.  1.  3.]
Ceiling:     [-1. -1. -0.  1.  2.  2.  3.]
Truncated:   [-1. -1. -0.  0.  1.  1.  3.]
Rounded:     [-2. -2. -0.  0.  2.  2.  3.]


3a)

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# ii
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

# iii.
smallest_4 =sorted_array[:4]
print("4 smallest elements:", smallest_4)

# iv.
largest_5 = np.sort(array)[-5:][::-1]
print("5 largest elements:", largest_5)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


3B)


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

#
int_ele = array[array % 1 == 0]
print("Integer elements:", int_ele)

#
float_ele = array[array % 1 != 0]
print("Float elements:", float_ele)


Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


4a)

In [77]:
from google.colab import files
uploaded = files.upload()


Saving download.jpeg to download.jpeg


In [78]:
from PIL import Image, ImageFile
import numpy as np

ImageFile.LOAD_TRUNCATED_IMAGES = True

def img_to_array(path):
    try:
        img = Image.open(path)
        img_arr = np.array(img)

        if img_arr.ndim == 2:
            print("Grayscale image detected")
            np.savetxt("image_grayscale.txt", img_arr, fmt='%d')
            return "grayscale"

        elif img_arr.ndim == 3:
            print("RGB image detected")
            flat = img_arr.reshape(-1, img_arr.shape[2])
            np.savetxt("image_rgb.txt", flat, fmt='%d')
            return "rgb"

        else:
            print("Image format not recognized")
            return None

    except Exception as e:
        print("Error:", e)
        return None

image_type = img_to_array("download.jpeg")

# Load the saved file based on type
if image_type == "grayscale":
    gray = np.loadtxt("image_grayscale.txt", dtype=int)
    print("Loaded grayscale shape:", gray.shape)
    print(gray[:5])  # Print only a part

elif image_type == "rgb":
    rgb = np.loadtxt("image_rgb.txt", dtype=int)
    print("Loaded RGB shape:", rgb.shape)
    print(rgb[:5])  # Print only a part

else:
    print("Could not load the saved image data.")

RGB image detected
Loaded RGB shape: (1091840, 3)
[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]
